# frozen_string_literal: true

require "fileutils"

module BetterAuth
  module Sinatra
    module Migration
      DEFAULT_MIGRATIONS_PATH = "db/better_auth/migrate"
      MISSING_MIGRATIONS_TABLE_MESSAGES = [
        /no such table/i,
        /relation .* does not exist/i,
        /table .* doesn't exist/i,
        /undefined table/i,
        /invalid object name/i
      ].freeze

      class UnsupportedAdapterError < StandardError; end

      module_function

      def render(options, dialect:)
        dialect = normalize_dialect(dialect)
        config = configuration_for(options)
        statements = BetterAuth::Schema::SQL.create_statements(config, dialect: dialect)
        [
          "-- Generated by better_auth-sinatra",
          "-- Dialect: #{dialect}",
          "",
          statements.join("\n\n"),
          ""
        ].join("\n")
      end

      def generate(options, dialect:, migrations_path: DEFAULT_MIGRATIONS_PATH, timestamp: Time.now.utc.strftime("%Y%m%d%H%M%S"))
        dialect = normalize_dialect(dialect)
        FileUtils.mkdir_p(migrations_path)
        path = File.join(migrations_path, "#{timestamp}_create_better_auth_tables.sql")
        return path if File.exist?(path)

        File.write(path, render(options, dialect: dialect))
        path
      end

      def migrate(auth_or_options, migrations_path: DEFAULT_MIGRATIONS_PATH)
        auth = auth_for(auth_or_options)
        adapter = auth.context.adapter
        unless adapter.respond_to?(:dialect) && adapter.respond_to?(:connection)
          raise UnsupportedAdapterError, "better_auth-sinatra migrations require core SQL adapters with connection and dialect support"
        end

        connection = adapter.connection
        dialect = normalize_dialect(adapter.dialect)
        files = Dir[File.join(migrations_path, "*.sql")].sort
        ensure_schema_migrations!(connection, dialect)
        applied = applied_migrations(connection, dialect)

        files.reject { |file| applied.include?(File.basename(file)) }.each do |file|
          execute_sql(connection, File.read(file))
          record_migration(connection, dialect, File.basename(file))
        end
      end

      def configuration_for(options)
        return options.options if options.is_a?(BetterAuth::Auth)
        return options if options.is_a?(BetterAuth::Configuration)

        BetterAuth::Configuration.new(options)
      end

      def auth_for(value)
        return value if value.is_a?(BetterAuth::Auth)

        BetterAuth.auth(value)
      end

      def ensure_schema_migrations!(connection, dialect)
        sql = case dialect
        when :postgres, :sqlite
          %(CREATE TABLE IF NOT EXISTS #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)} text PRIMARY KEY);)
        when :mysql
          %(CREATE TABLE IF NOT EXISTS #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)} varchar(191) PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;)
        when :mssql
          %(IF OBJECT_ID(N'#{quote("better_auth_schema_migrations", dialect)}', N'U') IS NULL CREATE TABLE #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)} varchar(255) PRIMARY KEY);)
        else
          raise UnsupportedAdapterError, "Unsupported SQL dialect for better_auth-sinatra migrations: #{dialect}"
        end
        execute_sql(connection, sql)
      end

      def applied_migrations(connection, dialect)
        rows = execute_sql(connection, "SELECT #{quote("version", dialect)} FROM #{quote("better_auth_schema_migrations", dialect)};")
        Array(rows).map { |row| row["version"] || row[:version] }
      rescue UnsupportedAdapterError
        raise
      rescue => error
        raise error unless missing_schema_migrations_table?(error)

        []
      end

      def record_migration(connection, dialect, version)
        sql = "INSERT INTO #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)}) VALUES (#{literal(version)});"
        execute_sql(connection, sql)
      end

      def execute_sql(connection, sql)
        statements(sql).each_with_object([]) do |statement, results|
          result =
            if connection.respond_to?(:exec)
              connection.exec(statement)
            elsif connection.respond_to?(:execute)
              connection.execute(statement)
            elsif connection.respond_to?(:query)
              connection.query(statement)
            else
              raise UnsupportedAdapterError, "SQL connection does not support exec, execute, or query"
            end
          results.concat(result.to_a) if result.respond_to?(:to_a)
        end
      end

      def statements(sql)
        normalized = sql.to_s.gsub("\r\n", "\n").strip
        return [] if normalized.empty?

        chunks = normalized.split(/;\s*\n/)
        chunks.flat_map do |chunk|
          chunk = chunk.strip
          next [] if chunk.empty?

          if chunk.include?(";") && !chunk.include?("\n")
            chunk.split(";").map(&:strip).reject(&:empty?)
          else
            [chunk.delete_suffix(";")]
          end
        end
      end

      def missing_schema_migrations_table?(error)
        message = error.message.to_s
        MISSING_MIGRATIONS_TABLE_MESSAGES.any? { |pattern| message.match?(pattern) }
      end

      def quote(identifier, dialect)
        BetterAuth::Schema::SQL.quote(identifier, dialect)
      end

      def literal(value)
        "'#{value.to_s.gsub("'", "''")}'"
      end

      def normalize_dialect(value)
        case value.to_s.downcase
        when "postgresql"
          :postgres
        when "sqlite3"
          :sqlite
        else
          value.to_sym
        end
      end
    end
  end
end
