name: Report an issue
description: Create a report to help us improve
body:
  - type: checkboxes
    attributes:
      label: Is this suited for github?
      description: Feel free to join the discord community [here](https://discord.gg/better-auth), we can usually respond faster to any questions.
      options:
        - label: Yes, this is suited for github
  - type: markdown
    attributes:
      value: |
        This template is used for reporting an issue with better-auth-ruby.

        Feature requests should be opened [here](https://github.com/better-auth/better-auth-ruby/issues/new?assignees=&labels=&projects=&template=feature_request.yml).

        Before opening a new issue, please do a [search](https://github.com/better-auth/better-auth-ruby/issues) of existing issues and :+1: upvote the existing issue instead. This will result in a quicker resolution.
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue. Screenshots can be provided in the issue body below.
      placeholder: |
        Ex:
        1. Set up authentication
        2. Try to login
        3. X error happens
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: A clear description of what the bug is and what you expected to happen.
      placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead.'
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Better Auth Ruby are you using?
      description: Please provide the current version of `better_auth` that you are reporting the bug on
      placeholder: "0.x.x"
    validations:
      required: true
  - type: textarea
    attributes:
      label: System info
      description: Output of `ruby -v` and `bundle list | grep better_auth`
      render: bash
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'Core'
        - 'Rails Adapter'
        - 'Documentation'
        - 'Other'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Auth configuration (if applicable)
      description: If applicable, please include your auth configuration. Make sure to remove any sensitive information.
      render: ruby
  - type: textarea
    attributes:
      label: Additional context
      description: Any extra information that might help us investigate.
