# frozen_string_literal: true

source "https://rubygems.org"

ruby file: "../../packages/better_auth/.ruby-version"

gem "better_auth", path: "../../packages/better_auth"
gem "better_auth-sinatra", path: "../../packages/better_auth-sinatra"

gem "puma"
gem "sinatra"
